apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-4eow
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/rs-demos-rhff-tenant/image-repository-cr-dotnet-component/devfile-sample-dotnet60-basic-4eow@sha256:8853454328fadc2c1c1b9e78ffc4c8c40db1af67fed3732f8f3fd15cae148874
        name: main
        resources: {}
status: {}
